### ISSUE TITLE
Playlist description fails to submit

### ISSUE THREAD

**Issue by numel007** [numel007/SPG-nodejs#17]
Spotify API doesn't throw an error on playlist creation, but it looks like playlist description doesn't submit at all.

**Comment by benchan777** [comment]
Pls fix. I can't tell what kind of music is in my playlist without a description.

**Comment by numel007** [comment]
Fixed in this [commit](https://github.com/numel007/SPG-nodejs/commit/cb012c340bf0eecf3b413bc9501ed17304bc6fa1).
